services:
  db:
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-heliotime}
  migration:
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-heliotime}
  importer:
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-heliotime}
  api:
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-heliotime}
