services:
  db:
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?Database password not specified}
  migration:
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?Database password not specified}
  importer:
    restart: unless-stopped
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?Database password not specified}
  api:
    restart: unless-stopped
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?Database password not specified}
  site:
    restart: unless-stopped
