services:
  db:
    image: timescale/timescaledb:2.15.2-pg16
    restart: unless-stopped
    healthcheck:
      # Do not use pg_isready because it throws errors
      # See: https://github.com/peter-evans/docker-compose-healthcheck/issues/16#issuecomment-1402807860
      test: ['CMD-SHELL', 'psql -h localhost -U $${POSTGRES_USER} -c select 1 -d $${POSTGRES_DB}']
      start_period: 10s
      interval: 10s
      retries: 10
    ports:
      - ${EXTERNAL_DATABASE_PORT:-5432}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME:-postgres}
      - POSTGRES_DB=${DATABASE_DATABASE:-postgres}
  server:
    build:
      context: ./server
    ports:
      - ${API_PORT:-8000}:8000
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_DATABASE=${DATABASE_DATABASE:-postgres}
      - DATABASE_USERNAME=${DATABASE_USERNAME:-postgres}
      - IMPORT_START=${IMPORT_START:-}
  site:
    build:
      context: ./site
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    ports:
      - ${SITE_PORT:-3000}:3000
    depends_on:
      - server
