name: heliotime-server
channels:
  - conda-forge
dependencies:
  - python=3.12
  - conda-lock=2.5

  # Base dependencies
  - fastapi=0.111
  - typer=0.12
  - sunpy=5.1
  - alembic=1.13
platforms:
  - linux-64
